import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 * Signal Model Class
 * 
 * Represents a trading signal generated by the Strategy Engine.
 * Contains signal type (BUY/SELL/HOLD), the instrument it applies to,
 * a confidence score, and the price at time of signal generation.
 * 
 * Part of the Observer Pattern — signals are produced by strategies
 * and consumed by TradeEngine, UI, and SignalLogger observers.
 */
public class Signal {

    // ─── Signal Types ────────────────────────────────────────────────
    public static final String BUY = "BUY";
    public static final String SELL = "SELL";
    public static final String HOLD = "HOLD";

    // ─── Fields ──────────────────────────────────────────────────────
    private String type;           // BUY, SELL, or HOLD
    private String instrument;     // e.g., "USD/INR", "EUR/USD"
    private double price;          // Price at signal generation
    private double confidence;     // Confidence level 0.0 - 1.0
    private String strategy;       // Name of strategy that generated this
    private String timestamp;      // When the signal was generated
    private String reason;         // Human-readable reasoning

    private static final DateTimeFormatter FORMATTER =
            DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

    // ─── Constructors ────────────────────────────────────────────────

    public Signal(String type, String instrument, double price, 
                  double confidence, String strategy, String reason) {
        this.type = type;
        this.instrument = instrument;
        this.price = price;
        this.confidence = Math.min(1.0, Math.max(0.0, confidence));
        this.strategy = strategy;
        this.reason = reason;
        this.timestamp = LocalDateTime.now().format(FORMATTER);
    }

    public Signal(String type, String instrument, double price, 
                  double confidence, String strategy) {
        this(type, instrument, price, confidence, strategy, "");
    }

    // ─── Getters ─────────────────────────────────────────────────────

    public String getType() { return type; }
    public String getInstrument() { return instrument; }
    public double getPrice() { return price; }
    public double getConfidence() { return confidence; }
    public String getStrategy() { return strategy; }
    public String getTimestamp() { return timestamp; }
    public String getReason() { return reason; }

    // ─── Serialization ───────────────────────────────────────────────

    public String toJSON() {
        return "{" +
                "\"type\":\"" + type + "\"," +
                "\"instrument\":\"" + instrument + "\"," +
                "\"price\":" + String.format("%.4f", price) + "," +
                "\"confidence\":" + String.format("%.2f", confidence) + "," +
                "\"strategy\":\"" + strategy + "\"," +
                "\"reason\":\"" + escapeJSON(reason) + "\"," +
                "\"timestamp\":\"" + timestamp + "\"" +
                "}";
    }

    private static String escapeJSON(String value) {
        if (value == null) return "";
        return value.replace("\\", "\\\\")
                     .replace("\"", "\\\"")
                     .replace("\n", "\\n");
    }

    @Override
    public String toString() {
        return String.format("[%s] %s %s @ %.4f (%.0f%% confidence, %s)",
                timestamp, type, instrument, price, confidence * 100, strategy);
    }
}
